name: NotaBene Pipeline

on: [push]

env:
  PROJ_SLUG: notabene

jobs:
  code-quality:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: notabene
          python-version: 3.8
      - name: Install Requirements
        run: |
          pip install pip-tools
          pip-sync
      - name: Formatting check using Black
        run:
          black . --check
      - name: Formatting check using ISort
        run:
          isort . --check-only
      - name: Linting check using Flake8
        run:
          flake8p $PROJ_SLUG tests
      - name: Linting check using PyLint
        run:
          pylint $PROJ_SLUG tests
      - name: Run all tests and coverage check
        run:
          pytest --cov=$PROJ_SLUG
  platform-validation:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: notabene
          python-version: 3.8
      - name: Install Requirements
        run: |
          pip install pip-tools
          pip-sync
      - name:
        run:
          tox -p