name: Platform Tests

on:
  push:
    branches:
      - main


env:
  # Increase this value to invalidate cache on this CI/CD pipeline
  CACHE_NUMBER: 3


jobs:
  platform-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - ubuntu-latest
#          - macos-latest
#          - windows-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: notabene
          python-version: 3.8
      - name: Setup Environment
        run:
          pip install pip-tools
      - name: Install Requirements
        run:
          pip-sync requirements.txt
      - name: Run tox to test grid of dependencies
        run:
          tox -p
        env:
          TOX_PARALLEL_NO_SPINNER: 1
