name: Platform Tests

on:
  pull_request:
    types:
      - labeled
      - opened
      - synchronize
      - reopened
    branches:
      - main
  push:
    branches:
      - main


env:
  # Increase this value to invalidate cache on this CI/CD pipeline
  CACHE_NUMBER: 4


jobs:
  platform-test:
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'platform-test'))
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - macos-latest
          - windows-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: notabene
          python-version: 3.8
      - name: Get Conda Path
        id: get-path
        run: echo "::set-output name=condapath::$(echo $CONDA_PREFIX)"
      - name: Cache env
        uses: actions/cache@v2
        with:
          path: ${{ steps.get-path.outputs.condapath }}
          key: conda-pt-${{ runner.os }}--${{ runner.arch }}-${{ hashFiles('requirements.txt') }}-${{ env.CACHE_NUMBER }}
        id: cache
      - name: Setup Environment
        run:
          pip install tox tox-conda -c requirements.txt
      - name: Run tox
        # Simply run tox sequentially, parallel was causing weird issues on some platforms
        run:
          tox
