name: Platform Tests

on:
  pull_request:
    types: [ labeled ]
    branches:
      - main
  push:
    branches:
      - main


env:
  # Increase this value to invalidate cache on this CI/CD pipeline
  CACHE_NUMBER: 4


jobs:
  platform-test:
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.event.label.name == 'platform-test')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - ubuntu-latest
#          - macos-latest
#          - windows-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: notabene
          python-version: 3.8
      - name: Setup Environment
        run:
          pip install tox tox-conda -c requirements.txt
      - name: Run tox to test grid of dependencies
        run:
          tox
        env:
          TOX_PARALLEL_NO_SPINNER: 1
