name: Publish PyPI

on:
  push:
    tags:
      - v**

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: notabene
        python-version: 3.8
    - name: Get Package Version
      id: package-version
      run: echo "::set-output name=version::v$(python setup.py --version)"
    - name: Check tag agains package version
      if: steps.package-version.outputs.version != github.ref
      run: exit 1
    - name: Setup Environment
      run:
        pip install twine -c requirements.txt
    - name: Package the code
      run:
        python setup.py sdist --dist-dir build/dist
    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
        packages_dir: build/dist/
        skip_existing: true